name: 'Automatically close stale issues'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
#Run every 6 hours

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: |-
            We are clearing up our old `help`-issues and your issue has been open for 60 days with no activity.
            If no comment is made and the stale label is not removed, this will be closed in 7 days.
          days-before-stale: 60
          days-before-close: 7
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-issue-labels: 'News,Medium,High,discussion,bug,doc,feature-request'
          exempt-issue-assignees: 'louislam'
          operations-per-run: 200
